# Generated by Django 3.2.11 on 2022-01-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20220130_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='wallet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finance.debtwallet'),
            preserve_default=False,
        ),
    ]
