# Generated by Django 3.2.11 on 2022-01-30 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_alter_debt_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='debtor',
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='welcome.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='finance.debtwallet'),
        ),
    ]
