# Generated by Django 3.2.11 on 2022-01-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_debt_debtwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='repay',
            field=models.FloatField(default=0),
        ),
    ]
