# Generated by Django 3.2.11 on 2022-01-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_debt_repay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='finance.debt')),
            ],
        ),
    ]
