# Generated by Django 3.2.11 on 2022-01-30 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0011_repay'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repay',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repay_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
