# Generated by Django 3.2.11 on 2022-01-31 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_auto_20220130_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'admin'), ('I', 'inhabitant'), ('G', 'guest')], max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_room', to='home.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
