# Generated by Django 3.2.11 on 2022-01-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('#21B6A8', 'blue-green'), ('#7EC8E3', 'baby-blue'), ('#868B8E', 'grey')], max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
